### PR TITLE
Add Visual Studio support

### PR DESCRIPTION
**Pull request by codylico**
This pull request adjusts some of the code to allow for compilation within Visual Studio.

### CODE REVIEW

**Review by alemart — CHANGES_REQUESTED** [review]
The `WIN32` flag in CMakeLists.txt is set to true when the target system is Windows. It may not be safe to assume that explicit linkage with libm is required only when `WIN32` is false.

There is probably a better way to check whether or not explicit linkage with libm is required. Perhaps with [CHECK_LIBRARY_EXISTS](https://cmake.org/cmake/help/latest/module/CheckLibraryExists.html)?

**Comment by codylico** [comment]
Sure. I can look into using `CHECK_LIBRARY_EXISTS` instead.

**Comment by codylico** [comment]
I have changed the CMake project file to use `CHECK_LIBRARY_EXISTS`. The project builds under both Windows and Linux.

**Review by alemart — APPROVED** [review]
Thank you!

**Pull request merged**
